# Generated by Django 2.2.4 on 2020-02-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0002_auto_20200121_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='total_max_amount',
            field=models.CharField(max_length=50),
        ),
    ]
